import Head from "next/head";
import Header from "@/pages/components/Header";
import SideBar from "@/pages/components/SideBar";
import React from "react";
import Hero from "@/pages/components/Hero/Hero";


const Home = () => {
  return (
    <>
      <Head>
        <title>JFC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero/>
        {/* <Highlights/> */}
        {/* <PoolCards/> */}
        {/* <SideBar /> */}
      </main>
    </>
  );
}

export default Home;
