import Head from "next/head";
import Header from "@/pages/components/Header";
import React from "react";
import Hero from "@/pages/components/Hero/Hero";
import PaymentSetup from "@/pages/components/PaymentSetup/PaymentSetup";


const Home = () => {
  return (
    <>
      <Head>
        <title>JFC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero/>
        <PaymentSetup onSubmit={() => {}} />
      </main>
    </>
  );
}

export default Home;
